@API_HostAddress = http://localhost:5031

GET {{API_HostAddress}}/api/user/ACD8BC15-E9FF-4BF8-B0AA-BFFB9C932984
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhY2Q4YmMxNS1lOWZmLTRiZjgtYjBhYS1iZmZiOWM5MzI5ODQiLCJlbWFpbCI6InRlc3QxOUB0ZXN0LmNvbSIsImV4cCI6MTc0NDI3NzQ4NSwiaXNzIjoiU29jaWFsTWVkaWEiLCJhdWQiOiJTb2NpYWxNZWRpYSJ9.8cDoYnn3Gzdtky01tXtr4Fb5LOGaT2wh2Fz7x6UGuvs


###
POST {{API_HostAddress}}/api/User/signup
Content-Type: application/json

{
  "FirstName": "MOh",
  "LastName": "Ko",
  "Email": "test22@test.com",
  "Password": "Aa@39888"
}

###
POST {{API_HostAddress}}/api/User/login
Content-Type: application/json

{
  "Email": "test19@test.com",
  "Password": "123456"
}


###
POST {{API_HostAddress}}/api/Auth/refresh-token
Content-Type: application/json

{
  "RefreshToken": "sznk7jWmgLEwW76YBRtZlCtJSxxGxyGR/8aRyW/xn5EapWK32Es725w5eBFpfsBC0mc9u4Sq0fcOdUPeBFjGsA=="
}


###
POST {{API_HostAddress}}/api/Auth/request-reset
Content-Type: application/json

{
  "Email": "test2@test.com"
}


###
POST {{API_HostAddress}}/api/Auth/reset-password
Content-Type: application/json

{
  "Token": "4xT9Vt9iflCnDuFU2M8/Fg+yx17I8k6sunxg4TttKXbS9XWJxbfakLFHkwk1UK7zY5pm19iFLKL28KflDDTKUw==",
  "NewPassword": "1234567"
}

###

# curl http://localhost:5031/health
GET {{API_HostAddress}}/health

###

