@API_HostAddress = http://localhost:5031

GET {{API_HostAddress}}/api/user/70ebadd4-e923-4584-b82f-52175d8c30db
Accept: application/json

###
POST {{API_HostAddress}}/api/User/signup
Content-Type: application/json

{
  "FirstName": "MOh",
  "LastName": "Ko",
  "Email": "test22@test.com",
  "Password": "Aa@39888"
}

###
POST {{API_HostAddress}}/api/User/login
Content-Type: application/json

{
  "Email": "test19@test.com",
  "Password": "123456"
}


###
POST {{API_HostAddress}}/api/Auth/refresh-token
Content-Type: application/json

{
  "RefreshToken": "LvCQ/gPA8LIeC4sNi0lsEpLCfV/5/U2Ktw+ghbIFQeBNq+6WWBuwwjjICkwyc6u1CZclFKvckgavylnd13PUAA=="
}


###
POST {{API_HostAddress}}/api/Auth/request-reset
Content-Type: application/json

{
  "Email": ""
}


###
POST {{API_HostAddress}}/api/Auth/reset-password
Content-Type: application/json

{
  "Token": "4xT9Vt9iflCnDuFU2M8/Fg+yx17I8k6sunxg4TttKXbS9XWJxbfakLFHkwk1UK7zY5pm19iFLKL28KflDDTKUw==",
  "NewPassword": "1234567"
}

###

# curl http://localhost:5031/health
GET {{API_HostAddress}}/health

###

