@API_HostAddress = http://localhost:5014

GET {{API_HostAddress}}/api/user/70ebadd4-e923-4584-b82f-52175d8c30db
Accept: application/json

###
POST http://localhost:5014/api/User/signup
Content-Type: application/json

{
  "FirstName": "Test User",
  "LastName": "Ko",
  "Email": "test9@test.com",
  "Password": "123456"
}