@API_HostAddress = http://localhost:5014

GET {{API_HostAddress}}/api/user/70ebadd4-e923-4584-b82f-52175d8c30db
Accept: application/json

###
POST http://localhost:5014/api/User/signup
Content-Type: application/json

{
  "FirstName": "MOh",
  "LastName": "Ko",
  "Email": "test20@test.com",
  "Password": "123456"
}

###
POST http://localhost:5014/api/User/login
Content-Type: application/json

{
  "Email": "test20@test.com",
  "Password": "123456"
}


###
POST http://localhost:5014/api/Auth/refresh-token
Content-Type: application/json

{
  "RefreshToken": "2nONgUkDSb8IjymUBplEKfvO14TLofPkYUKA7JA2j3VbFEm0mZSEXyWyDPbt+xT9LczCT7izUBlnS20Xn/YkeQ=="
}


###
POST http://localhost:5014/api/Auth/request-reset
Content-Type: application/json

{
  "Email": "test20@test.com"
}


###
POST http://localhost:5014/api/Auth/reset-password
Content-Type: application/json

{
  "Token": "4xT9Vt9iflCnDuFU2M8/Fg+yx17I8k6sunxg4TttKXbS9XWJxbfakLFHkwk1UK7zY5pm19iFLKL28KflDDTKUw==",
  "NewPassword": "1234567"
}