@API_HostAddress = http://localhost:5014

GET {{API_HostAddress}}/api/user/1
Accept: application/json

###
POST http://localhost:5014/api/User/signup
Content-Type: application/json

{
  "UserName": "Test User",
  "Email": "test2@test.com",
  "Password": "123456"
}